FROM node:current-bookworm
ARG MAXMIND_LICENSE_KEY
ENV MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY?notset}
ENV AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID?notset}
ENV AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET?notset}
ENV AUTH_SECRET=${AUTH_SECRET?notset}
ENV AUTH_TRUST_HOST=${AUTH_TRUST_HOST?notset}
ENV BASE_URL=${BASE_URL?notset}
ENV MONGODB_URI=${MONGODB_URI?notset}
ENV PORT=${PORT?notset}
ENV REDIS_URL=${REDIS_URL?notset}
WORKDIR /app
COPY package.json ./
RUN npm install
WORKDIR /app/node_modules/geoip-lite
RUN npm run-script updatedb license_key=$MAXMIND_LICENSE_KEY
WORKDIR /app
COPY . .
EXPOSE 7871
CMD ["npm", "start"]

