version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - BASE_URL=${BASE_URL}
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


