FROM node:current-bookworm
ARG MAXMIND_LICENSE_KEY
ENV MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY?-}
ARG AUTH_GOOGLE_ID
ENV AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID?-}
ARG AUTH_GOOGLE_SECRET
ENV AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET?-}
ARG AUTH_SECRET
ENV AUTH_SECRET=${AUTH_SECRET?-}
ARG AUTH_TRUST_HOST
ENV AUTH_TRUST_HOST=${AUTH_TRUST_HOST?-}
ARG BASE_URL
ENV BASE_URL=${BASE_URL?-}
ARG MONGODB_URI
ENV MONGODB_URI=${MONGODB_URI?-}
ARG PORT
ENV PORT=${PORT?-}
ARG REDIS_URL
ENV REDIS_URL=${REDIS_URL?-}
WORKDIR /app
COPY package.json ./
RUN npm install
WORKDIR /app/node_modules/geoip-lite
RUN npm run-script updatedb license_key=$MAXMIND_LICENSE_KEY
WORKDIR /app
COPY . .
EXPOSE 7871
CMD ["npm", "start"]

