services:
  web:
    image: ${DOCKER_USERNAME}/shortie:latest
    build: .
    ports:
      - "7871:7871"
    depends_on:
      - redis
    environment:
      - NODE_ENV=${NODE_ENV:-production} # Default to 'production' if not set
      - PORT=7871
    env_file:
      - .env
    networks:
      - rednet
  redis:
    image: "redis:latest"
    networks:
      - rednet


networks:
  rednet:
      driver: bridge
