services:
  web:
    image: ${DOCKER_USERNAME}/shortie:${LATEST_TAG}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAXMIND_LICENSE_KEY=${MAXMIND_LICENSE_KEY}
    ports:
      - "7871:7871"
    depends_on:
      - redis
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=7871
    env_file:
      - .env.production
    networks:
      - rednet
  redis:
    image: "redis:latest"
    networks:
      - rednet


networks:
  rednet:
      driver: bridge
