name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTH_GOOGLE_ID: {{ secrets.AUTH_GOOGLE_ID }}
      AUTH_GOOGLE_SECRET: {{ secrets.AUTH_GOOGLE_SECRET }}
      AUTH_SECRET: {{ secrets.AUTH_SECRET }}
      AUTH_TRUST_HOST: {{ secrets.AUTH_TRUST_HOST }}
      BASE_URL: {{ secrets.BASE_URL }}
      DOCKER_USERNAME: {{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: {{ secrets.DOCKER_PASSWORD }}
      MAXMIND_LICENSE_KEY: {{ secrets.MAXMIND_LICENSE_KEY }}
      MONGODB_URI: {{ secrets.MONGODB_URI }}
      PORT: {{ secrets.PORT }}
      REDIS_URL: {{ secrets.REDIS_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build Docker images
        run: docker-compose build

      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main' # Only push on main branch pushes
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker-compose push

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_PRIVATE_KEY }}
          script: |
            #Login on DO server
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker-compose pull
            docker-compose down
            docker-compose up -d
